# Connecting to SQLite
spring.datasource.url=jdbc:sqlite:file:memdb1?mode=memory&cache=shared
spring.datasource.driver-class-name=org.sqlite.JDBC

# Disable DDL check (SQLite does not support all DDL commands)
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.open-in-view=false

# create == DELETE ALL TABLES and create them anew
spring.jpa.hibernate.ddl-auto=create

# Goggle Sheets API Configuration
google.sheets.credential.path=classpath:test-project-475020-48b97ca0c299.json
google.sheets.spreadsheet.id=1qjNoN04vNetRizsy6hJjTjIBfS_FpgfwxFB9YyN4w-A
google.sheets.application.name=AutoDocs

app.config.path=/config/default_config.ini
app.constants.path=/config/constants.ini
