package ru.nsu.astakhov.autodocs.integration.google.scanner;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@RequiredArgsConstructor
@Getter
public enum InternshipColumnType {
    FULL_NAME(0),
    SPECIALIZATION(1),
    GROUP_NAME(2),
    INTERNSHIP_TYPE(3),
    THESIS_SUPERVISOR_NAME(4),
    THESIS_SUPERVISOR_POSITION(5),
    THESIS_SUPERVISOR_DEGREE(6),
    THESIS_SUPERVISOR_TITLE(7),
    FULL_ORGANIZATION_NAME(8),
    NSU_SUPERVISOR_NAME(9),
    NSU_SUPERVISOR_POSITION(10),
    NSU_SUPERVISOR_DEGREE(11),
    NSU_SUPERVISOR_TITLE(12),
    ORGANIZATION_SUPERVISOR_NAME(13),
    ORGANIZATION_SUPERVISOR_POSITION(14),
    ORGANIZATION_SUPERVISOR_DEGREE(15),
    ORGANIZATION_SUPERVISOR_TITLE(16),
    ADMINISTRATIVE_ACT_FROM_ORGANIZATION(17),
    FULL_PLACE_OF_INTERNSHIP(18),
    ORGANIZATION_NAME(19),
    EMAIL(20),
    EDU_PROGRAM(21),
    ACTUAL_SUPERVISOR(22),
    DATE_OF_PRACTICE_ASSIGNMENT(24);

    private final int columnNumber;
}
